name: "Homepage"
version: "0.9.6"
slug: "homepage"
description: "A customizable dashboard for your smart home."
image: "ghcr.io/gethomepage/homepage:latest"
arch:
  - amd64
  - armv7
  - aarch64
startup: "services"
boot: "auto"
ports:
  3000/tcp: 3000
options:
  config_path: "/config/homepage"  # Home Assistant config directory for persistent storage
  docker_sock: "/var/run/docker.sock"
schema:
  config_path: str
  docker_sock: str
volumes:
  - /config/homepage:/app/config
  - /var/run/docker.sock:/var/run/docker.sock