name: "Homepage"
version: "0.9.6"
slug: "homepage"
description: "A customizable dashboard for your smart home."
arch:
  - amd64
  - armv7
  - aarch64
startup: "services"
boot: "auto"
ports:
  3000/tcp: 3000
options: {}
schema: {}
image: "ghcr.io/benphelps/homepage:latest"