name: "Dashy"
version: "1.0.0"
slug: "dashy"
description: "A customizable personal dashboard app"
arch:
  - amd64
  - armv7
  - aarch64
startup: "services"
boot: "auto"
ports:
  8080/tcp: 8080
options: {}
schema: {}
image: "lissy93/dashy:latest"